# Generated by Django 5.2.7 on 2025-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpoolpost',
            name='text',
        ),
        migrations.AddField(
            model_name='carpoolpost',
            name='dropoff',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carpoolpost',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carpoolpost',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carpoolpost',
            name='pickup',
            field=models.TextField(default=''),
        ),
    ]
