# Generated by Django 5.2.7 on 2025-11-07 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_carpoolpost_text_carpoolpost_dropoff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolpost',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='carpoolpost',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carpoolpost',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
