# Generated by Django 5.2.7 on 2025-11-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_carpoolpost_date_alter_carpoolpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolpost',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
