# Generated by Django 5.2.7 on 2025-11-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_carpoolpost_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolpost',
            name='dropoff_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carpoolpost',
            name='pickup_time',
            field=models.TextField(default=''),
        ),
    ]
