# Generated by Django 3.2.25 on 2025-12-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolpost',
            name='dropoff_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='carpoolpost',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
