# Generated by Django 5.2.7 on 2025-11-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
