# Generated by Django 5.2.7 on 2025-10-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile_riderprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
