# Generated by Django 3.2.25 on 2025-12-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20251121_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='computing_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
