# Generated by Django 4.2.25 on 2025-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='is_seen_by_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='is_seen_by_rider',
            field=models.BooleanField(default=True),
        ),
    ]
